version: "3.8"
services:
  webapp:
    build: .
    # volumes:
    #   - .:/project
    ports:
      - 443:3000

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./containers/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    ports:
      - 8883:1883

  # TODO
  # Add RabbitMQ broker?
  # Port 5671
