version: "3.8"
services:
  webapp:
    build: .
    # volumes:
    #   - .:/project
    ports:
      - 443:443 # SSL
      - 3000:3000

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./containers/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    ports:
      # [M]essage [Q]ueuing [T]elemetry [T]ransport protocol
      - 1883:1883 # MQTT
      - 8883:1883 # MQTTS # TODO

  # TODO
  # Add RabbitMQ broker?
  # Port 5671 # AMQPS protocol over TLS/SSL
  # Port 5672 # AMQP protocol over TLS/SSL
