additional_info="file:///etc/product-info.toml"

hostname = FIXME
trust_bundle_cert = "file:///var/aziot/certs/azure-iot.root.ca.cert.pem"
auto_reprovisioning_mode = "AlwaysOnStartup"


[provisioning]
source = "manual"
iothub_hostname = FIXME.azure-devices.net
device_id = FIXME

[provisioning.authentication]
method = "x509"

identity_cert = "file:///var/aziot/certs/iot-edge-device-identity-full-chain.cert.pem"
identity_pk = "file:///var/aziot/secrets/iot-edge-device-identity.key.pem"


[edge_ca]
cert = "file:///var/aziot/certs/iot-edge-device-ca-full-chain.cert.pem"
pk = "file:///var/aziot/secrets/iot-edge-device-ca.key.pem"
